# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# this file is auto-generated by the Frappe framework
from frappe import _

app_name = "golbazaar"
app_title = "Golbazaar"
app_publisher = "Your Name"
app_description = "Custom Golbazaar App"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "your.email@example.com"
app_license = "mit"

# Apps
# ------------------

# required_apps = []

# Each item in the list will be shown as an app in the apps page
# add_to_apps_screen = [
# 	{
# 		"name": "golbazaar",
# 		"title": "Golbazaar",
# 		"route": "/golbazaar/dashboard"
# 	}
# ]

# Includes in <head>
# ------------------

# include js, css files in header of desk.html
# No global React assets; standard Frappe dashboard
# app_include_css = "/assets/golbazaar/css/golbazaar.css"
# app_include_js = "/assets/golbazaar/js/golbazaar.js"

# include js, css files in header of web template
# web_include_css = "/assets/golbazaar/css/golbazaar.css"
# web_include_js = "/assets/golbazaar/js/golbazaar.js"

# include custom scss in every website theme (without file extension ".scss")
# website_theme_scss = "golbazaar/public/scss/website"

# include js, css files in header of web form
# webform_include_js = {"doctype": "public/js/doctype.js"}
# webform_include_css = {"doctype": "public/css/doctype.css"}

# include js in page
# page_js = {"page" : "public/js/file.js"}

# include js in doctype views
# doctype_js = {"doctype" : "public/js/doctype.js"}
# doctype_list_js = {"doctype" : "public/js/doctype_list.js"}
# doctype_tree_js = {"doctype" : "public/js/doctype_tree.js"}
# doctype_calendar_js = {"doctype" : "public/js/doctype_calendar.js"}

# Svg Icons
# ------------------
# include app icons in desk
# app_include_icons = "golbazaar/public/icons.svg"

# Home Pages
# ----------

# application home page (will override Website Settings)
# home_page = "login"

# website user home page (by Role)
# role_home_page = {
# 	"Role": "home_page"
# }

# Generators
# ----------

# automatically create page for each record of this doctype
# website_generators = ["Web Page"]

# Jinja
# ----------

# add methods and filters to jinja environment
# jinja = {
# 	"methods": "golbazaar.utils.jinja_methods",
# 	"filters": "golbazaar.utils.jinja_filters"
# }

# Installation
# ------------

# before_install = "golbazaar.install.before_install"
after_install = "golbazaar.install.after_install"

# Uninstallation
# ------------

# before_uninstall = "golbazaar.uninstall.before_uninstall"
# after_uninstall = "golbazaar.uninstall.after_uninstall"

# Integration Setup
# ------------------
# To set up dependencies/integrations with other apps
# Name of the app being installed is passed as an argument

# before_app_install = "golbazaar.utils.before_app_install"
# after_app_install = "golbazaar.utils.after_app_install"

# Integration Cleanup
# -------------------
# To clean up dependencies/integrations with other apps
# Name of the app being uninstalled is passed as an argument

# before_app_uninstall = "golbazaar.utils.before_app_uninstall"
# after_app_uninstall = "golbazaar.utils.after_app_uninstall"

# Desk Notifications
# ------------------
# See frappe.core.notifications.get_notification_config

# notification_config = "golbazaar.notifications.get_notification_config"

# Permissions
# -----------
# Permissions evaluated in scripted ways

# permission_query_conditions = {
# 	"Event": "frappe.desk.doctype.event.event.get_permission_query_conditions",
# }
#
# has_permission = {
# 	"Event": "frappe.desk.doctype.event.event.has_permission",
# }

# DocType Class
# ---------------
# Override standard doctype classes

override_doctype_class = {
	"POS Invoice": "golbazaar.pos_invoice_override.CustomPOSInvoice"
}

# Document Events
# ---------------
# Hook on document methods and events

# doc_events = {
# 	"*": {
# 		"on_update": "method",
# 		"on_cancel": "method",
# 		"on_trash": "method"
# 	}
# }

# Scheduled Tasks
# ---------------

# scheduler_events = {
# 	"all": [
# 		"golbazaar.tasks.all"
# 	],
# 	"daily": [
# 		"golbazaar.tasks.daily"
# 	],
# 	"hourly": [
# 		"golbazaar.tasks.hourly"
# 	],
# 	"weekly": [
# 		"golbazaar.tasks.weekly"
# 	],
# 	"monthly": [
# 		"golbazaar.tasks.monthly"
# 	],
# }

# Testing
# -------

# before_tests = "golbazaar.install.before_tests"

# Overriding Methods
# ------------------------------
#
# override_whitelisted_methods = {
# 	"frappe.desk.doctype.event.event.get_events": "golbazaar.event.get_events"
# }
#
# each overriding function accepts a `data` argument;
# generated from the base implementation of the doctype dashboard,
# along with any modifications made in other Frappe apps
# override_doctype_dashboards = {
# 	"Task": "golbazaar.task.get_dashboard_data"
# }

# exempt linked doctypes from being automatically cancelled
#
# auto_cancel_exempted_doctypes = ["Auto Repeat"]

# Ignore links to specified DocTypes when deleting documents
# -----------------------------------------------------------

# ignore_links_on_delete = ["Communication", "ToDo"]

# Request Events
# ----------------
# before_request = ["golbazaar.utils.before_request"]
# after_request = ["golbazaar.utils.after_request"]

# Job Events
# ----------
# before_job = ["golbazaar.utils.before_job"]
# after_job = ["golbazaar.utils.after_job"]

# User Data Protection
# --------------------

# user_data_fields = [
# 	{
# 		"doctype": "{doctype_1}",
# 		"filter_by": "{filter_by}",
# 		"redact_fields": ["{field_1}", "{field_2}"],
# 		"partial": 1,
# 	},
# 	{
# 		"doctype": "{doctype_2}",
# 		"filter_by": "{filter_by}",
# 		"partial": 1,
# 	},
# 	{
# 		"doctype": "{doctype_3}",
# 		"strict": False,
# 	},
# 	{
# 		"doctype": "{doctype_4}"
# 	}
# ]

# Authentication and authorization
# --------------------------------

# auth_hooks = [
# 	"golbazaar.auth.validate"
# ]

# Automatically update python controller files with type annotations for this app.
# export_python_type_annotations = True

# default_log_clearing_doctypes = {
# 	"Logging DocType Name": 30  # days to retain logs
# }

# App Data


# ---------
fixtures = [
    "Workspace",
    "Custom Field",
]
def get_data():
	return [
		{
			"label": _("Golbazaar"),
			"icon": "octicon octicon-file-directory",
			"items": [
				{
					"type": "doctype",
					"name": "Golbazaar Settings",
					"description": _("Golbazaar Settings"),
				}
			]
		}
	]

